CREATE OR REPLACE PROCEDURE PROYECTO1.LLENAR_CLIENTES (CANTIDAD IN NUMBER) IS

    PERSONA_ID PROYECTO1.PERSONAS.ID%TYPE;
    CANT_PERSONAS NUMBER;
    
BEGIN

    SELECT COUNT(*) INTO CANT_PERSONAS FROM PROYECTO1.PERSONAS WHERE ID NOT IN (
        SELECT PERSONA_ID FROM PROYECTO1.CLIENTES 
    );
    
    IF CANTIDAD < CANT_PERSONAS THEN
        CANT_PERSONAS := CANTIDAD;
    END IF;
        
    FOR PERSONA IN (
        SELECT ID FROM PROYECTO1.PERSONAS WHERE ID NOT IN (
            SELECT PERSONA_ID FROM PROYECTO1.CLIENTES 
        ) AND ROWNUM <= CANT_PERSONAS
    ) LOOP
        INSERT INTO PROYECTO1.CLIENTES (PERSONA_ID) VALUES (PERSONA.ID);
    END LOOP;
    
END;

-- ** 

BEGIN 
    PROYECTO1.LLENAR_CLIENTES(5000);
END;

SELECT COUNT(*) FROM PROYECTO1.CLIENTES;

SELECT * FROM PROYECTO1.CLIENTES;

DELETE FROM PROYECTO1.CLIENTES WHERE 1=1;
