CREATE OR REPLACE PROCEDURE PROYECTO1.LLENAR_DIRECCIONES (CANTIDAD IN NUMBER) IS

    PERSONA_ID      PROYECTO1.PERSONAS.ID%TYPE;
    DISTRITO_ID     PROYECTO1.DISTRITOS.ID%TYPE;
    CANT_PERSONAS   NUMBER;
    
BEGIN

    SELECT COUNT(*) INTO CANT_PERSONAS FROM PROYECTO1.PERSONAS WHERE ID NOT IN (
        SELECT PERSONA_ID FROM PROYECTO1.DIRECCIONES 
    );
    
    IF CANTIDAD < CANT_PERSONAS THEN
        CANT_PERSONAS := CANTIDAD;
    END IF;
        
    FOR PERSONA IN (
        SELECT ID FROM PROYECTO1.PERSONAS WHERE ID NOT IN (
            SELECT PERSONA_ID FROM PROYECTO1.DIRECCIONES 
        ) AND ROWNUM <= CANT_PERSONAS
    ) LOOP
        SELECT ID INTO DISTRITO_ID FROM (
            SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
        ) WHERE ROWNUM = 1;
        INSERT INTO PROYECTO1.DIRECCIONES (PERSONA_ID, DISTRITO_ID) VALUES (PERSONA.ID, DISTRITO_ID);
    END LOOP;
    
END;

-- **

DECLARE

    CANT_PERSONAS NUMBER;

BEGIN 
    SELECT COUNT(ID) INTO CANT_PERSONAS FROM PROYECTO1.PERSONAS;
    PROYECTO1.LLENAR_DIRECCIONES(CANT_PERSONAS);
END;

SELECT COUNT(*) FROM PROYECTO1.DIRECCIONES;

SELECT * FROM PROYECTO1.DIRECCIONES;

DELETE FROM PROYECTO1.DIRECCIONES WHERE 1=1;