CREATE OR REPLACE PROCEDURE PROYECTO1.LLENAR_EMPLEADOS (CANTIDAD IN NUMBER) IS

    PERSONA_ID PROYECTO1.PERSONAS.ID%TYPE;
    CANT_PERSONAS NUMBER;
    SALARIO PROYECTO1.EMPLEADOS.SALARIO%TYPE;
    
BEGIN

    SELECT COUNT(*) INTO CANT_PERSONAS FROM PROYECTO1.PERSONAS WHERE ID NOT IN (
        SELECT PERSONA_ID FROM PROYECTO1.EMPLEADOS 
    );
    
    IF CANTIDAD < CANT_PERSONAS THEN
        CANT_PERSONAS := CANTIDAD;
    END IF;
        
    FOR PERSONA IN (
        SELECT ID FROM PROYECTO1.PERSONAS WHERE ID NOT IN (
            SELECT PERSONA_ID FROM PROYECTO1.EMPLEADOS 
        ) AND ROWNUM <= CANT_PERSONAS
    ) LOOP
        SELECT (1000 + ABS(MOD(DBMS_RANDOM.RANDOM, 10000000))) INTO SALARIO FROM DUAL;
        INSERT INTO PROYECTO1.EMPLEADOS (PERSONA_ID, SALARIO) VALUES (PERSONA.ID, SALARIO);
    END LOOP;
    
END;

-- ** 

BEGIN 
    PROYECTO1.LLENAR_EMPLEADOS(15);
END;

SELECT * FROM PROYECTO1.EMPLEADOS;

DELETE FROM PROYECTO1.EMPLEADOS WHERE 1=1;
