CREATE OR REPLACE PROCEDURE PROYECTO1.LLENAR_FECHAS (FECHA_INICIAL IN DATE, FECHA_FINAL IN DATE) IS

    MES         PROYECTO1.FECHAS.MES%TYPE;
    NOMBRE_MES  PROYECTO1.FECHAS.NOMBRE_MES%TYPE;
    ANNIO       PROYECTO1.FECHAS.ANNIO%TYPE;
    DIA_SEMANA  PROYECTO1.FECHAS.DIA_SEMANA%TYPE;
    DIA_ANNIO   PROYECTO1.FECHAS.DIA_ANNIO%TYPE;
    
    FECHA_INICIAL_AUX   PROYECTO1.FECHAS.FECHA%TYPE := TO_DATE(FECHA_INICIAL, 'DD/MM/YYYY');
    FECHA_FINAL_AUX     PROYECTO1.FECHAS.FECHA%TYPE := TO_DATE(FECHA_FINAL, 'DD/MM/YYYY');
    
BEGIN

    WHILE FECHA_INICIAL_AUX <= FECHA_FINAL_AUX LOOP
            
        SELECT TO_CHAR(FECHA_INICIAL_AUX, 'MM') INTO MES FROM DUAL;
        SELECT TO_CHAR(FECHA_INICIAL_AUX, 'MONTH') INTO NOMBRE_MES FROM DUAL;
        SELECT TO_CHAR(FECHA_INICIAL_AUX, 'YYYY') INTO ANNIO FROM DUAL;
        SELECT TO_CHAR(FECHA_INICIAL_AUX, 'D') INTO DIA_SEMANA FROM DUAL;
        SELECT TO_CHAR(FECHA_INICIAL_AUX, 'DDD') INTO DIA_ANNIO FROM DUAL;
        
        INSERT INTO PROYECTO1.FECHAS (FECHA, MES, NOMBRE_MES, ANNIO, DIA_SEMANA, DIA_ANNIO)
            VALUES (FECHA_INICIAL_AUX, MES, NOMBRE_MES, ANNIO, DIA_SEMANA, DIA_ANNIO);
        
        FECHA_INICIAL_AUX := FECHA_INICIAL_AUX + 1;
    END LOOP;
    
END;

-- ** 

BEGIN 
    PROYECTO1.LLENAR_FECHAS('01/01/2017', '31/12/2020');
END;

SELECT * FROM PROYECTO1.FECHAS ORDER BY FECHA;

SELECT COUNT(*) FROM PROYECTO1.FECHAS;

DELETE FROM PROYECTO1.FECHAS WHERE 1=1;
