select * from proyecto1.cantones
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),13,'TIBAS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),14,'MORAVIA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),12,'ACOSTA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),10,'ALAJUELITA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),11,'VAZQUEZ DE CORONADO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),15,'MONTES DE OCA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),19,'PEREZ ZELEDON');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),20,'LEON CORTES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),18,'CURRIDABAT');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),16,'TURRUBARES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),17,'DOTA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),9,'SANTA ANA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),3,'DESAMPARADOS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),4,'PURISCAL');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),1,'SAN JOSE');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),2,'ESCAZU');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),7,'MORA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),8,'GOICOECHEA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),5,'TARRAZU');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 1 and rownum = 1),6,'ASERRI');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),12,'VALVERDE VEGA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),11,'ZARCERO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),10,'SAN CARLOS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),13,'UPALA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),14,'LOS CHILES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),15,'GUATUSO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),3,'GRECIA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),9,'OROTINA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),1,'ALAJUELA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),2,'SAN RAMON');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),4,'SAN MATEO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),5,'ATENAS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),8,'POAS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),7,'PALMARES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 2 and rownum = 1),6,'NARANJO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),6,'ALVARADO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),5,'TURRIALBA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),8,'EL GUARCO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),7,'OREAMUNO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),2,'PARAISO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),1,'CARTAGO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),4,'JIMENEZ');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 3 and rownum = 1),3,'LA UNION');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),1,'HEREDIA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),8,'FLORES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),7,'BELEN');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),10,'SARAPIQUI');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),9,'SAN PABLO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),6,'SAN ISIDRO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),3,'SANTO DOMINGO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),2,'BARVA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),5,'SAN RAFAEL');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 4 and rownum = 1),4,'SANTA BARBARA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),8,'TILARAN');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),7,'ABANGARES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),9,'NANDAYURE');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),11,'HOJANCHA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),10,'LA CRUZ');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),6,'Ca¿as');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),2,'NICOYA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),1,'LIBERIA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),3,'SANTA CRUZ');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),5,'CARRILLO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 5 and rownum = 1),4,'BAGACES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),3,'BUENOS AIRES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),2,'ESPARZA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),1,'PUNTARENAS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),10,'CORREDORES');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),9,'PARRITA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),8,'COTO BRUS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),11,'GARABITO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),5,'OSA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),4,'MONTES DE ORO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),7,'GOLFITO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 6 and rownum = 1),6,'QUEPOS');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 7 and rownum = 1),1,'LIMON');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 7 and rownum = 1),5,'MATINA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 7 and rownum = 1),6,'GUACIMO');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 7 and rownum = 1),4,'TALAMANCA');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 7 and rownum = 1),2,'POCOCI');
insert into proyecto1.cantones (provincia_id, codigo, nombre) values ((select id from proyecto1.provincias where codigo = 7 and rownum = 1),3,'SIQUIRRES');