
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744102950031, 'HOT DOG AJON', 1, 900, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744102950776, 'BIMBOLLO 4P', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744102955677, 'PAN CUA BIMB', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744101164123, 'PASTA LUCEMA', 1, 660, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0000000004664, 'TOMATE GRANE 1KG', 1, 2200, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0000000004562, 'ZANAHORIA SU 1KG', 1, 600, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107410056, 'CHILE DULC E', 1, 950, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107411458, 'MANZAN RO E', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107825751, 'PAPA EMP 1KG', 1, 890, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0000000004665, 'CEBOLLA GRAN 1KG', 1, 2700, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0000000004060, 'BROCOLI EMP 1KG', 1, 3500, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0000000004597, 'PEPINO GRAN 1KG', 1, 630, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100162048, 'YOG DEL FRES', 1, 16, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0075307910084, 'GAMA CLUBMAX', 1, 750, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744116340343, 'MARIA INTEGR', 1, 660, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0770242580764, 'TOALLA KOTEX', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100815674, 'KOTEX DAYS L', 1, 570, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107822724, 'GALLET CHOCO', 1, 170, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107412255, 'CHAYOTE TIER', 1, 400, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744101109165, 'COMBO K', 1, 2870, , 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0085551700601, 'IMITAC QUESO', 1, 900, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744102020787, 'PRONOL220MG', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107822139, 'CEREA AR', 1, 170, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100333255, 'TORT ZRG 10U', 1, 3100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107822727, 'GALLETA SODA', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0762221086453, 'TANG MANZAN', 1, 10, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107825512, 'CAFE GV PURO', 1, 160, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100162328, 'NECT DP SURT', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0075196317004, 'MARGARINA BA', 1, 530, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0075196321210, 'CLOVER MANT', 1, 440, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0073170104249, 'PASTA ROMA', 1, 800, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0075196331125, 'SOYA 950ML', 1, 980, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0761303663317, 'SAZO NATU 4P', 1, 320, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0761303574134, 'MAGGI CONSOM', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0001497911117, 'CHOP S VIGUI', 1, 140, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0741100034502, 'SALS CRI LIZ', 1, 150, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0007874243367, 'GV CREM CAF', 1,  2250, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0073505100060, 'HEINZ 6PACK', 1, 190, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107415239, 'ARROZ ENT IN', 1, 3300, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107825667, 'INDIAN FRJ N', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0741003139292, 'CALVO VEGETA', 1, 950, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0073170101444, 'ATUN TROZOS', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0079650000139, 'GARBANZO 576', 1, 710, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0750177097202, 'POLV HORNEAR', 1, 920, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107822717, 'SARDINA 160G', 1, 550, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100260100, 'SARD SDM SAL', 1, 600, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744107823103, 'TOALLA COCIN', 1, 900, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100817259, 'SCOTT PAPEL', 1, 120, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0750103291549, 'TIRAS ACTIVA', 1, 900, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100780034, 'SUPER GATO', 1, 3100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100031208, 'CLORO CLOROX', 1, 100, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0009917626397, 'LAVAPLAT CRE', 1, 130, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0744100037178, 'POETT DESINF', 1, 2470, 100);
INSERT INTO PROYECTO1.PRODUCTOS (PROVEEDOR_ID, CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, INVENTARIO) 
	VALUES ((
			SELECT ID FROM (
				SELECT ID FROM PROYECTO1.PROVEEDORES ORDER BY DBMS_RANDOM.VALUE
			) WHERE ROWNUM = 1
		), 0740106813180, 'HUEVSUPT 30U', 1, 2000, 100);

-- **

BEGIN
	FOR PRODUCTO IN (
		SELECT * FROM PROYECTO1.PRODUCTOS
	) LOOP

		UPDATE PROYECTO1.PRODUCTOS SET PRECIO_COMPRA = (PRODUCTO.PRECIO_VENTA * 0.7)
			WHERE ID = PRODUCTO.ID;

	END LOOP;
END;

SELECT * FROM PROYECTO1.PRODUCTOS