select * from proyecto1.distritos;
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),1	,'SANTA BARBARA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),3	,'SAN JUAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),4	,'JESUS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),1	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),2	,'SAN JOSECITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),4	,'ANGELES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),5	,'CONCEPCION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),2	,'SAN JOSE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),3	,'CONCEPCION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),1	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),1	,'SAN JOAQUIN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),2	,'BARRANTES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),1	,'SAN PABLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,1	,'PUERTO VIEJO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,3	,'LAS HORQUETAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),4	,'NACASCOLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),5	,'CURUBANDE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),2	,'MANSION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),3	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),5	,'SAMARA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),6	,'NOSARA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),1	,'SANTA CRUZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),4	,'TEMPATE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),5	,'CARTAGENA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),6	,'CUAJINIQUIL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),8	,'CABO VELAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),2	,'LA FORTUNA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),1	,'FILADELFIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),3	,'SARDINAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),4	,'BELEN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),1	,'LAS JUNTAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),2	,'SIERRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),1	,'TILARAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),3	,'TRONADORA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),4	,'SANTA ROSA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),5	,'LIBANO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),6	,'TIERRAS MORENAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),7	,'ARENAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),1	,'CARMONA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),2	,'SANTA RITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),3	,'ZAPOTAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),4	,'SAN PABLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),5	,'PORVENIR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),6	,'BEJUCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,2	,'SANTA CECILIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,3	,'LA GARITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,4	,'SANTA ELENA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,1	,'HOJANCHA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),1	,'PUNTARENAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),3	,'CHOMES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),4	,'LEPANTO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),5	,'PAQUERA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),6	,'MANZANILLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),9	,'MONTE VERDE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),1	,'ESPIRITU SANTO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),2	,'SAN JUAN GRANDE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),3	,'MACACONA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),1	,'BUENOS AIRES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),2	,'VOLCAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),5	,'PILAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),6	,'COLINAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),7	,'CHANGUENA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),2	,'LA UNION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),3	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),3	,'SIERPE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),2	,'SAVEGRE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),3	,'NARANJITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),2	,'PUERTO JIMENEZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),3	,'GUAYCARA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),3	,'AGUA BUENA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),4	,'LIMONCITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),1	,'PARRITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,1	,'CORREDOR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,3	,'CANOAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,2	,'TARCOLES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),1	,'GUAPILES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),3	,'RITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),4	,'ROXANA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),5	,'CARIARI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),2	,'PACUARITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),4	,'GERMANIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),5	,'EL CAIRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),2	,'SIXAOLA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),3	,'CAHUITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),1	,'MATINA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),1	,'GUACIMO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),2	,'MERCEDES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),4	,'RIO JIMENEZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),5	,'DUACARI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),3	,'HOSPITAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),6	,'SN.FCO.DOS RIOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),7	,'URUCA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),9	,'PAVAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),10	,'HATILLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),11	,'SAN SEBASTIAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),4	,'BEBEDERO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),3	,'SAN MIGUEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),2	,'PALMIRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),10	,'TRES EQUIS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),11	,'LA ISABEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,4	,'LEON XIII', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),5	,'SARDINAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),7	,'SARDINAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,4	,'HUACAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,3	,'PUERTO CARRILLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),9	,'TAMARINDO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),7	,'BELEN DE NOSARITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,4	,'LLANURAS DEL GASPAR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),3	,'RIO BLANCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),4	,'TELIRE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),5	,'LLANOS DE SANTA LUCIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),8	,'ESCOBAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),14	,'ACAPULCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),13	,'CHIRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),7	,'SALITRILLOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),13	,'LOS GUIDO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 20 and rownum = 1)	,6	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 16 and rownum = 1)	,5	,'CARARA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),9	,'BRUNKA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),16	,'ARANCIBIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,4	,'LAUREL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),14	,'SARAPIQUI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),7	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),11	,'CONCEPCION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),2	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),5	,'TACARES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),1	,'SAN MATEO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),1	,'ATENAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),4	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),4	,'CIRRI SUR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),1	,'PALMARES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),4	,'SANTIAGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),1	,'SAN PEDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),4	,'CARRILLOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),3	,'HACIENDA VIEJA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,2	,'FLORENCIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,6	,'PITAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,9	,'LA PALMERA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,12	,'MONTERREY', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,6	,'ZAPOTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,3	,'TORO AMARILLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,2	,'AGUAS CLARAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,6	,'DOS RIOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 14 and rownum = 1)	,3	,'EL AMPARO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,2	,'BUENAVISTA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),3	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),4	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),8	,'SAN CRISTOBAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),1	,'SANTIAGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),9	,'CHIRES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),3	,'SAN CARLOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),3	,'VUELTA DE JORCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),2	,'GUAYABO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),5	,'PICAGRES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),4	,'MATA DE PLATANO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),3	,'POZOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),5	,'PIEDADES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,3	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,2	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,5	,'SABANILLAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,3	,'ANSELMO LLORENTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,2	,'SABANILLA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 16 and rownum = 1)	,1	,'SAN PABLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 17 and rownum = 1)	,1	,'SANTA MARIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 18 and rownum = 1)	,2	,'GRANADILLA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,2	,'EL GENERAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,5	,'SAN PEDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,9	,'BARU', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,11	,'PARAMO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 20 and rownum = 1)	,3	,'LLANO BONITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),6	,'GUADALUPE O ARENILLA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),10	,'LLANO GRANDE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),3	,'OROSI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),2	,'SAN DIEGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),5	,'CONCEPCION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),1	,'JUAN VINAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),2	,'LA SUIZA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),5	,'SANTA TERESITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),1	,'PACAYAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),1	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),5	,'SANTA ROSA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),4	,'ULLOA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),2	,'SAN PEDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),6	,'S.JOSE DE LA M.', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),4	,'PARACITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),8	,'PARA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),2	,'SAN PEDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),6	,'PURABA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),3	,'SANTIAGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),1	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),2	,'LA RIBERA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),3	,'LLORENTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,2	,'LA VIRGEN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 0	 and rownum = 1),0	,'NO REGISTRADO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,4	,'KATIRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),1	,'NICOYA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),4	,'QUEBRADA HONDA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),3	,'VEINTISIETE DE ABRIL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),7	,'DIRIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),1	,'BAGACES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),2	,'PALMIRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),1	,'CANAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),3	,'SAN JUAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),2	,'QUEBRADA GRANDE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),8	,'BARRANCA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),4	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),3	,'POTRERO GRANDE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),1	,'MIRAMAR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),1	,'PUERTO CORTES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),1	,'QUEPOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),1	,'GOLFITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),5	,'PITTIER', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,2	,'LA CUESTA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),1	,'LIMON', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),2	,'JIMENEZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),6	,'COLORADO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),1	,'BRATSI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),3	,'CARRANDI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),3	,'POCORA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),2	,'MERCED', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),5	,'ZAPOTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),8	,'MATA REDONDA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),5	,'SAN GERONIMO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),5	,'POROZAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),12	,'CHIRRIPO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),6	,'SARDINAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,2	,'MONTE ROMO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),4	,'SAN FRANCISCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),4	,'MATAMA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),8	,'BRIOLLEY', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),4	,'BAHIA BALLENA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),12	,'GRAVILIAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,5	,'COLIMA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),15	,'EL ROBLE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),4	,'PAVON', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),10	,'ISLA DEL COCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),5	,'GUACIMA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),13	,'GARITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),1	,'HEREDIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),1	,'LIBERIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),7	,'GUACIMAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),2	,'VALLE LA ESTRELLA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),2	,'SAN JOSE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),9	,'RIO SEGUNDO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),6	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),4	,'SAN ROQUE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),3	,'MERCEDES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),5	,'SAN JERONIMO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),2	,'SAN JUAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,1	,'QUESADA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,10	,'VENADO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,5	,'PALMIRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,4	,'BIJAGUA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,1	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),5	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),4	,'GRIFO ALTO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),2	,'TARBACA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),1	,'GUADALUPE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),4	,'URUCA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,5	,'SAN FELIPE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,1	,'SAN JUAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,3	,'MERCEDES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 18 and rownum = 1)	,1	,'CURRIDABAT', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,7	,'PEJIBAYE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),1	,'ORIENTAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),11	,'QUEBRADILLA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),6	,'DULCE NOMBRE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),6	,'PAVONES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),3	,'POTRERO CERRADO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),1	,'BARVA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),2	,'SAN VICENTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),5	,'SANTO DOMINGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),3	,'LA ASUNCION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),2	,'CANAS DULCES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),2	,'BOLSON', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),3	,'MOGOTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),4	,'COLORADO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,1	,'LA CRUZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),2	,'PITAHAYA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),11	,'COBANO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),4	,'BORUCA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),2	,'PALMAR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),2	,'SABALITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,1	,'JACO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),1	,'SIQUIRRES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),2	,'BATAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),4	,'CATEDRAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),6	,'ALEGRIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),4	,'RIO NARANJO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,5	,'CUREÑA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,7	,'BRISAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),7	,'PURRAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),5	,'PIEDRAS BLANCAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),1	,'NARANJO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,3	,'TAPESCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),5	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,1	,'SAN IGNACIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),2	,'OCCIDENTAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),4	,'PATIO DE AGUA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),3	,'MAYORGA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),2	,'SANTIAGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),1	,'SAN RAMON', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),1	,'CARMEN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),1	,'ALAJUELA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),3	,'SAN JUAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),3	,'CARRIZAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),4	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),6	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),7	,'SABANILLA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),8	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),10	,'DESAMPARADOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),11	,'TURRUCARES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),12	,'TAMBOR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),4	,'PIEDADES NORTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),5	,'PIEDADES SUR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),8	,'ANGELES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),9	,'ALFARO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),10	,'VOLIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),12	,'ZAPOTAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),13	,'PENAS BLANCAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),1	,'GRECIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),3	,'SAN JOSE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),6	,'RIO CUARTO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),7	,'PUENTE DE PIEDRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),8	,'BOLIVAR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),2	,'DESMONTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),3	,'JESUS MARIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),2	,'JESUS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),5	,'CONCEPCION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),6	,'SAN JOSE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),7	,'SANTA EULALIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),2	,'SAN MIGUEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),3	,'SAN JOSE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),6	,'SAN JUAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),7	,'EL ROSARIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),2	,'ZARAGOZA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),3	,'BUENOS AIRES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),5	,'CANDELARIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),6	,'ESQUIPULAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),7	,'LA GRANJA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),3	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),5	,'SABANA REDONDA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),1	,'OROTINA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),2	,'EL MASTATE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),4	,'COYOLAR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),5	,'LA CEIBA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,3	,'BUENAVISTA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,4	,'AGUAS ZARCAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,5	,'VENECIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,7	,'LA FORTUNA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,8	,'LA TIGRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,11	,'CUTRIS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,13	,'POCOSOL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,1	,'ZARCERO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,2	,'LAGUNA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,4	,'GUADALUPE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,1	,'SARCHI NORTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,2	,'SARCHI SUR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,4	,'SAN PEDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,5	,'RODRIGUEZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,1	,'UPALA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,3	,'SAN JOSE O PIZOTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,5	,'DELICIAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,7	,'YOLILLAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 14 and rownum = 1)	,1	,'LOS CHILES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 14 and rownum = 1)	,2	,'CANO NEGRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 14 and rownum = 1)	,4	,'SAN JORGE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,3	,'COTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),1	,'ESCAZU', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),2	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),1	,'DESAMPARADOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),2	,'SAN MIGUEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),3	,'S.JUAN DE DIOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),6	,'FRAILES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),7	,'PATARRA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),9	,'ROSARIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),10	,'DAMAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),11	,'SN.RAFAEL ABAJO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),2	,'MERCEDES SUR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),3	,'BARBACOAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),6	,'CANDALARITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),7	,'DESAMPARADITOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),8	,'SAN ANTONIO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),1	,'SAN MARCOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),2	,'SAN LORENZO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),1	,'ASERRI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),4	,'SAN GABRIEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),5	,'LEGUA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),6	,'MONTERREY', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),1	,'COLON', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),3	,'TABARCIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),4	,'PIEDRAS NEGRAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),2	,'SAN FRANCISCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),3	,'CALLE BLANCOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),5	,'IPIS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),6	,'RANCHO REDONDO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),1	,'SANTA ANA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),2	,'SALITRAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 9	 and rownum = 1),6	,'BRASIL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,1	,'ALAJUELITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,2	,'SAN JOSECITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 10 and rownum = 1)	,4	,'CONCEPCION', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,1	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,3	,'DULCE NOMBRE DE JESUS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,4	,'PATALILLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 11 and rownum = 1)	,5	,'CASCAJAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,2	,'GUAITIL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,3	,'PALMICHAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 12 and rownum = 1)	,4	,'CANGREJAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 13 and rownum = 1)	,2	,'CINCO ESQUINAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 14 and rownum = 1)	,1	,'SAN VICENTE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 14 and rownum = 1)	,2	,'SAN JERONIMO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 14 and rownum = 1)	,3	,'LA TRINIDAD', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,1	,'SAN PEDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 15 and rownum = 1)	,4	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 16 and rownum = 1)	,2	,'SAN PEDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 16 and rownum = 1)	,3	,'SAN JUAN DE MATA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 16 and rownum = 1)	,4	,'SAN LUIS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 17 and rownum = 1)	,2	,'EL JARDIN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 17 and rownum = 1)	,3	,'COPEY', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 18 and rownum = 1)	,3	,'SANCHEZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,1	,'SAN ISIDRO DE EL GENERAL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,3	,'DANIEL FLORES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,4	,'RIVAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,6	,'PLATANARES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,8	,'CAJON', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 20 and rownum = 1)	,1	,'SAN PABLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 20 and rownum = 1)	,2	,'SAN ANDRES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 20 and rownum = 1)	,4	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 20 and rownum = 1)	,5	,'SANTA CRUZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),3	,'CARMEN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),4	,'SAN NICOLAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),5	,'AGUACALIENTE O SAN FRANCISCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),7	,'CORRALILLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),8	,'TIERRA BLANCA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),9	,'DULCE NOMBRE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),1	,'PARAISO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),2	,'SANTIAGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),4	,'CACHI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),1	,'TRES RIOS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),3	,'SAN JUAN', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),4	,'SAN RAFAEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),7	,'SAN RAMON', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),8	,'RIO AZUL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),2	,'TUCURRIQUE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 4	 and rownum = 1),3	,'PEJIBAYE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),1	,'TURRIALBA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),3	,'PERALTA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),4	,'SANTA CRUZ', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),7	,'TUIS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),8	,'TAYUTIC', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 5	 and rownum = 1),9	,'SANTA ROSA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),2	,'CERVANTES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 6	 and rownum = 1),3	,'CAPELLADES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),2	,'COT', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 7	 and rownum = 1),4	,'CIPRESES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),1	,'EL TEJAR', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),2	,'SAN ISIDRO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),3	,'TOBOSI', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),2	,'MERCEDES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),3	,'SAN FRANCISCO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),5	,'VARABLANCA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),3	,'SAN PABLO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),4	,'SAN ROQUE', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 2	 and rownum = 1),5	,'SANTA LUCIA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),1	,'SANTO DOMINGO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),3	,'SAN MIGUEL', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),5	,'SANTO TOMAS', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),6	,'SANTA ROSA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),7	,'TURES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 1	 and rownum = 1),12	,'CHACARITA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 8	 and rownum = 1),1	,'SAN VITO', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 3	 and rownum = 1),3	,'FLORIDA', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 18 and rownum = 1)	,4	,'TIRRASES', 1);
insert into proyecto1.distritos (canton_id	, codigo, nombre	, codigo_postal) values ((select id from proyecto1.cantones where codigo = 19 and rownum = 1)	,10	,'RIO NUEVO', 1);