SELECT * FROM PROYECTO1.PROVEEDORES;


INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'BIMBO'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'CHEMSOL S.A.'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'COREMAR'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'ALGO PICANTE'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'ALIMENTOS PROSALUD'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'QUESO PALMITO COSTA RICA'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'RICO RICO'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'CERVECERÍA DE COSTA RICA'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'FANAL'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'COCA COLA COMPANY'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'PIPASA'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'CARNICERÍA EL BUEN PEDAZO'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'DISTRIBUIDORA LA ISLEÑA'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'TABACALERA NACIONAL'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'NESTLÉ'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'POZUELO'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'DOS PINOS'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'DILOMOSA'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'PANIFICADORA DOÑA MERRY'
);
INSERT INTO PROYECTO1.PROVEEDORES (DISTRITO_ID, NOMBRE) VALUES (
    (SELECT ID FROM (
        SELECT ID FROM PROYECTO1.DISTRITOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1),
    'JHONSON Y JHONSON'
);

