DECLARE
    FECHA_INICIAL DATE := TO_DATE('01/01/2017', 'DD/MM/YYYY');
    FECHA_FINAL DATE := TO_DATE('31/12/2017', 'DD/MM/YYYY');
BEGIN

WHILE FECHA_INICIAL <= FECHA_FINAL LOOP
    LLENAR_VENTAS(5000, FECHA_INICIAL);
    FECHA_INICIAL := FECHA_INICIAL + 1;
END LOOP;

END;
