-- SUCURSALES

CREATE TABLE PROYECTO1.SUCURSALES (
	ID INT NOT NULL,
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE PROYECTO1.SUCURSALES_ID_SEQ;

CREATE TRIGGER PROYECTO1.SUCURSALES_ID 
    BEFORE INSERT ON PROYECTO1.SUCURSALES FOR EACH ROW
BEGIN
    SELECT PROYECTO1.SUCURSALES_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

-- PERSONAS

CREATE TABLE PROYECTO1.PERSONAS (
	ID INT NOT NULL,
	CEDULA INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(50) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
	FEC_NACIMIENTO DATE NOT NULL,
	ESTADO_CIVIL INT NOT NULL,
	SEXO INT NOT NULL,
	OCUPACION INT NOT NULL,
	EDUCACION INT NOT NULL,
	HIJOS INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE PROYECTO1.PERSONAS_ID_SEQ;

CREATE TRIGGER PROYECTO1.PERSONAS_ID 
    BEFORE INSERT ON PROYECTO1.PERSONAS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.PERSONAS_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

--EMPLEADOS

CREATE TABLE PROYECTO1.EMPLEADOS (
	ID INT NOT NULL,
	PERSONA_ID INT NOT NULL,
	CODIGO INT NOT NULL,
	SALARIO INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT EMPLEADO_PERSONA_ID_FK FOREIGN KEY (PERSONA_ID)
        REFERENCES PROYECTO1.PERSONAS (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.EMPLEADOS_ID_SEQ;

CREATE TRIGGER PROYECTO1.EMPLEADOS_ID 
    BEFORE INSERT ON PROYECTO1.EMPLEADOS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.EMPLEADOS_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

CREATE SEQUENCE PROYECTO1.EMPLEADOS_CODIGO_SEQ;

CREATE TRIGGER PROYECTO1.EMPLEADOS_CODIGO 
    BEFORE INSERT ON PROYECTO1.EMPLEADOS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.EMPLEADOS_CODIGO_SEQ.nextval
    INTO :new.CODIGO
    FROM dual;
END;

-- CLIENTES

CREATE TABLE PROYECTO1.CLIENTES (
	ID INT NOT NULL,
	PERSONA_ID NOT NULL,
	CODIGO INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CLINTE_PERSONA_ID_FK FOREIGN KEY (PERSONA_ID)
        REFERENCES PROYECTO1.PERSONAS (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.CLIENTES_ID_SEQ;

CREATE TRIGGER PROYECTO1.CLIENTES_ID 
    BEFORE INSERT ON PROYECTO1.CLIENTES FOR EACH ROW
BEGIN
    SELECT PROYECTO1.CLIENTES_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

CREATE SEQUENCE PROYECTO1.CLIENTES_CODIGO_SEQ;

CREATE TRIGGER PROYECTO1.CLIENTES_CODIGO 
    BEFORE INSERT ON PROYECTO1.CLIENTES FOR EACH ROW
BEGIN
    SELECT PROYECTO1.CLIENTES_CODIGO_SEQ.nextval
    INTO :new.CODIGO
    FROM dual;
END;

--PROVINCIAS

CREATE TABLE PROYECTO1.PROVINCIAS (
	ID INT NOT NULL,
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE PROYECTO1.PROVINCIAS_ID_SEQ;

CREATE TRIGGER PROYECTO1.PROVINCIA_ID 
    BEFORE INSERT ON PROYECTO1.PROVINCIAS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.PROVINCIAS_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

--CANTONES

CREATE TABLE PROYECTO1.CANTONES (
	ID INT NOT NULL,
	PROVINCIA_ID INT NOT NULL,
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CANTON_PROVINCIA_ID_FK FOREIGN KEY (PROVINCIA_ID)
        REFERENCES PROYECTO1.PROVINCIAS (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.CANTONES_ID_SEQ;

CREATE TRIGGER PROYECTO1.CANTONES_ID 
    BEFORE INSERT ON PROYECTO1.CANTONES FOR EACH ROW
BEGIN
    SELECT PROYECTO1.CANTONES_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

--DISTRITOS

CREATE TABLE PROYECTO1.DISTRITOS (
	ID INT NOT NULL,
	CANTON_ID INT NOT NULL,
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CODIGO_POSTAL INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT DISTRITO_CANTON_ID FOREIGN KEY (CANTON_ID)
        REFERENCES PROYECTO1.CANTONES (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.DISTRITOS_ID_SEQ;

CREATE TRIGGER PROYECTO1.DISTRITOS_ID 
    BEFORE INSERT ON PROYECTO1.DISTRITOS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.DISTRITOS_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

-- DIRECCIONES

CREATE TABLE PROYECTO1.DIRECCIONES (
	ID INT NOT NULL,
	PERSONA_ID INT NOT NULL,
	DISTRITO_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT DIRECCION_PERSONA_ID FOREIGN KEY (PERSONA_ID)
        REFERENCES PROYECTO1.PERSONAS (ID) ON DELETE CASCADE,
    CONSTRAINT DIRECCION_DISTRITO_ID FOREIGN KEY (DISTRITO_ID)
        REFERENCES PROYECTO1.DISTRITOS (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.DIRECCIONES_ID_SEQ;

CREATE TRIGGER PROYECTO1.DIRECCIONES_ID 
    BEFORE INSERT ON PROYECTO1.DIRECCIONES FOR EACH ROW
BEGIN
    SELECT PROYECTO1.DIRECCIONES_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

--PROVEEDORES

CREATE TABLE PROYECTO1.PROVEEDORES (
	ID INT NOT NULL,
	DISTRITO_ID INT NOT NULL,
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PROVEEDOR_DISTRITO_ID FOREIGN KEY (DISTRITO_ID)
        REFERENCES PROYECTO1.DISTRITOS (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.PROVEEDORES_ID_SEQ;

CREATE TRIGGER PROYECTO1.PROVEEDORES_ID 
    BEFORE INSERT ON PROYECTO1.PROVEEDORES FOR EACH ROW
BEGIN
    SELECT PROYECTO1.PROVEEDORES_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

CREATE SEQUENCE PROYECTO1.PROVEEDORES_CODIGO_SEQ;

CREATE TRIGGER PROYECTO1.PROVEEDORES_CODIGO 
    BEFORE INSERT ON PROYECTO1.PROVEEDORES FOR EACH ROW
BEGIN
    SELECT PROYECTO1.PROVEEDORES_CODIGO_SEQ.nextval
    INTO :new.CODIGO
    FROM dual;
END;

-- PRODUCTOS

CREATE TABLE PROYECTO1.PRODUCTOS (
	ID INT NOT NULL,
	PROVEEDOR_ID INT NOT NULL,
	CODIGO INT NOT NULL,
	NOMBRE VARCHAR (50) NOT NULL,
	PRECIO_COMPRA INT NOT NULL,
	PRECIO_VENTA INT NOT NULL,
	INVENTARIO INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT PRODUCTO_PROVEEDOR_ID FOREIGN KEY (PROVEEDOR_ID)
        REFERENCES PROYECTO1.PROVEEDORES (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.PRODUCTOS_ID_SEQ;

CREATE TRIGGER PROYECTO1.PRODUCTOS_ID 
    BEFORE INSERT ON PROYECTO1.PRODUCTOS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.PRODUCTOS_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

-- FECHAS

CREATE TABLE PROYECTO1.FECHAS (
	ID INT NOT NULL,
	FECHA DATE NOT NULL,
	MES INT NOT NULL, 
	NOMBRE_MES VARCHAR (20) NOT NULL,
	ANNIO INT NOT NULL,
	DIA_SEMANA INT NOT NULL,
	DIA_ANNIO INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE PROYECTO1.FECHAS_ID_SEQ;

CREATE TRIGGER PROYECTO1.FECHAS_ID 
    BEFORE INSERT ON PROYECTO1.FECHAS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.FECHAS_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

-- VENTAS

CREATE TABLE PROYECTO1.VENTAS (
	ID INT NOT NULL,
	SUCURSAL_ID INT NOT NULL,
	PRODUCTO_ID INT NOT NULL,
	CLIENTE_ID INT NOT NULL,
	EMPLEADO_ID INT NOT NULL,
	FECHA_ID INT NOT NULL,
	CODIGO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	TOTAL INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT VENTA_SUCURSAL_ID FOREIGN KEY (SUCURSAL_ID)
        REFERENCES PROYECTO1.SUCURSALES (ID) ON DELETE CASCADE,
    CONSTRAINT VENTA_PRODUCTO_ID FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PROYECTO1.PRODUCTOS (ID) ON DELETE CASCADE,
    CONSTRAINT VENTA_CLIENTE_ID FOREIGN KEY (CLIENTE_ID)
        REFERENCES PROYECTO1.CLIENTES (ID) ON DELETE CASCADE,
    CONSTRAINT VENTA_EMPLEADO_ID FOREIGN KEY (EMPLEADO_ID)
        REFERENCES PROYECTO1.EMPLEADOS (ID) ON DELETE CASCADE,
    CONSTRAINT VENTA_FECHA_ID FOREIGN KEY (FECHA_ID)
        REFERENCES PROYECTO1.FECHAS (ID) ON DELETE CASCADE
);

CREATE SEQUENCE PROYECTO1.VENTAS_ID_SEQ;

CREATE TRIGGER PROYECTO1.VENTAS_ID 
    BEFORE INSERT ON PROYECTO1.VENTAS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.VENTAS_ID_SEQ.nextval
    INTO :new.ID
    FROM dual;
END;

CREATE SEQUENCE PROYECTO1.VENTAS_CODIGO_SEQ;

CREATE TRIGGER PROYECTO1.VENTAS_CODIGO 
    BEFORE INSERT ON PROYECTO1.VENTAS FOR EACH ROW
BEGIN
    SELECT PROYECTO1.VENTAS_CODIGO_SEQ.nextval
    INTO :new.CODIGO
    FROM dual;
END;