USE UTNSA;

SELECT * FROM SA_CLIENTES;
SELECT * FROM SA_PERSONAS;

SELECT 
	C.ID AS ID,
	P.CEDULA AS CEDULA,
	P.NOMBRE + ' ' + P.APELLIDOS AS NOMBRE,
	P.CORREO AS CORREO,
	P.FEC_NACIMIENTO AS FEC_NACIMIENTO,
	CASE P.ESTADO_CIVIL 
		WHEN 0 THEN 'SOLTERO' 
		WHEN 1 THEN 'CASADO' 
		ELSE 'N/A' END
	AS ESTADO_CIVIL,
	CASE P.SEXO
		WHEN 1 THEN 'MASCULINO' 
		WHEN 2 THEN 'FEMENINO' 
		ELSE 'N/A' END
	AS SEXO,
	CASE P.OCUPACION
		WHEN 1 THEN ''
		WHEN 2 THEN ''
		WHEN 3 THEN ''
		WHEN 4 THEN ''
		WHEN 5 THEN ''
		ELSE 'N/A' END
	AS OCUPACION,
	CASE P.EDUCACION
		WHEN 1 THEN ''
		WHEN 2 THEN ''
		WHEN 3 THEN ''
		WHEN 4 THEN ''
		WHEN 5 THEN ''
		ELSE 'N/A' END
	AS EDUCACION,
	P.HIJOS AS HIJOS
FROM 
	SA_CLIENTES C,
	SA_PERSONAS P
WHERE
	C.PERSONA_ID = P.ID;