CREATE OR REPLACE PROCEDURE PROYECTO1.LLENAR_VENTAS (V_CANTIDAD IN NUMBER, V_FECHA IN PROYECTO1.FECHAS.FECHA%TYPE) IS

    SUCURSAL_ID     PROYECTO1.SUCURSALES.ID%TYPE;
    PRODUCTO_ID     PROYECTO1.PRODUCTOS.ID%TYPE;
    CLIENTE_ID      PROYECTO1.PERSONAS.ID%TYPE;
    EMPLEADO_ID     PROYECTO1.PERSONAS.ID%TYPE;
    FECHA_ID        PROYECTO1.FECHAS.ID%TYPE;
    CANTIDAD        PROYECTO1.VENTAS.CANTIDAD%TYPE;
    TOTAL           PROYECTO1.VENTAS.TOTAL%TYPE;
    
BEGIN

FOR DATOS IN 1 .. V_CANTIDAD LOOP

    SELECT ID INTO SUCURSAL_ID FROM (
        SELECT ID FROM PROYECTO1.SUCURSALES ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1;
    
    SELECT ID INTO PRODUCTO_ID FROM (
        SELECT ID FROM PROYECTO1.PRODUCTOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1;
    
    SELECT ID INTO CLIENTE_ID FROM (
        SELECT ID FROM PROYECTO1.CLIENTES ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1;
    
    SELECT ID INTO EMPLEADO_ID FROM (
        SELECT ID FROM PROYECTO1.EMPLEADOS ORDER BY DBMS_RANDOM.VALUE
    ) WHERE ROWNUM = 1;
    
    SELECT ID INTO FECHA_ID FROM (
        SELECT ID FROM PROYECTO1.FECHAS F WHERE F.FECHA = V_FECHA
    ) WHERE ROWNUM = 1;
    
    SELECT (1 + ABS(MOD(DBMS_RANDOM.RANDOM, 100))) INTO CANTIDAD FROM DUAL;
    
    SELECT PRECIO_VENTA * CANTIDAD INTO TOTAL FROM (
        SELECT P.PRECIO_VENTA
        FROM PROYECTO1.PRODUCTOS P
        WHERE P.CODIGO = PRODUCTO_ID
    ) WHERE ROWNUM = 1;
    
    INSERT INTO PROYECTO1.VENTAS 
        (SUCURSAL_ID, PRODUCTO_ID, CLIENTE_ID, EMPLEADO_ID, FECHA_ID, CANTIDAD, TOTAL)
    VALUES
        (SUCURSAL_ID, PRODUCTO_ID, CLIENTE_ID, EMPLEADO_ID, FECHA_ID, CANTIDAD, TOTAL);

END LOOP;

END;